CREATE TABLE T37A (
 Nome varchar (50) NULL
)

GO

CREATE TABLE T37B (
  Nome varchar (50) NULL
)

INSERT INTO T37A VALUES ('Miguel')
INSERT INTO T37A VALUES ('Pedro')
INSERT INTO T37A VALUES ('Juliana')
INSERT INTO T37A VALUES ('Anderson')
INSERT INTO T37A VALUES ('Gustavo')
INSERT INTO T37A VALUES ('Natanael')
SELECT * FROM T37A

INSERT INTO T37B VALUES ('Rafael')
INSERT INTO T37B VALUES ('Luiz')
INSERT INTO T37B VALUES ('Atilio')
INSERT INTO T37B VALUES ('Tiago')
INSERT INTO T37B VALUES ('Natanael')
INSERT INTO T37B VALUES ('Neri')
SELECT * FROM T37B


SELECT A.Nome, B.Nome 
FROM T37A AS A
FULL OUTER JOIN T37B AS B
on a.Nome = b.Nome

SELECT A.nome, B.nome
FROM T37A as A
JOIN T37B as B
on a.Nome = b.Nome